# Generated by Django 4.2.6 on 2023-10-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModel',
            fields=[
                ('id_dataset', models.AutoField(primary_key=True, serialize=False)),
                ('nama_dataset', models.CharField(max_length=100)),
                ('kategori_dataset', models.CharField(choices=[('heart_disease', 'Heart Disease'), ('stroke', 'Stroke')], max_length=50)),
                ('link_dataset', models.CharField(max_length=250)),
                ('field_count', models.IntegerField(default=0)),
                ('field_list', models.TextField(null=True)),
                ('data_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeartDiseaseDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('cp', models.IntegerField(default=0)),
                ('trtbps', models.IntegerField(default=0)),
                ('chol', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('restecg', models.IntegerField(default=0)),
                ('thalachh', models.IntegerField(default=0)),
                ('exng', models.IntegerField(default=0)),
                ('oldpeak', models.IntegerField(default=0)),
                ('slp', models.IntegerField(default=0)),
                ('caa', models.IntegerField(default=0)),
                ('thall', models.IntegerField(default=0)),
                ('output', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('model_algorithm', models.CharField(choices=[('decision_tree', 'Decision Tree')], default='decision_tree', max_length=50)),
                ('parameter_count', models.IntegerField(default=0)),
                ('parameter_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedModelPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_model', models.CharField(max_length=50)),
                ('kategori_model', models.CharField(max_length=50)),
                ('akurasi', models.FloatField()),
                ('recall', models.FloatField()),
                ('path_model', models.CharField(max_length=50)),
                ('id_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='api.datasetmodel')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_type', to='api.modelprediction')),
            ],
        ),
    ]
