# Generated by Django 4.2.6 on 2023-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_dataset_generatedmodelprediction_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseasedatamodel',
            name='oldpeak',
            field=models.FloatField(default=0),
        ),
    ]
